### ISSUE TITLE
Add Industrial Foregoing

### ISSUE THREAD

**Issue by FreakinKen** [DocCyblade/squirrelpak-mc12#13]
Industrial Foregoing adds critical in game opportunities. Items such as the plant sower, plant gatherer, hydrator, fertilizer, and more allows for automated farms which can make a base look even more productive and efficient. On top of that, we have items like the block breaker and the block placer that allows you to simplify placing and breaking items early game before refined storage. 

On top of this, we have everything enchantments! We have things like the enchantment factory, applicator, extractor and the sorter! This allows for for all things enchanting which is one of the only mods that allows this form of enchanting. 

We haven't even touched on of the most awesome features! We have the mob imprisonment tool! This placed in a mob duplicator allows us to reproduce and farm mobs, then with the mob crusher we can farm them.

**Comment by DocCyblade** [comment]
I agree this would be a good fit. However its already loading red on 2.5G of ram where we want. We may need to remove something that creates a lot of blocks/items if it spikes over 2.5G usages. I will run some tests and post findings

**Comment by DocCyblade** [comment]
This would add two mods, mod will require Tesla Core Lib as well
