### ISSUE TITLE
Do config files persist on the client through server pack updates?

### ISSUE THREAD

**Issue by FreakinKen** [DocCyblade/squirrelpak-mc12#55]
What the title says....

**Comment by DocCyblade** [comment]
We will test this next update Beta Two - Make sure you have changed you settings for drop item and if it changes back we know

**Comment by DocCyblade** [comment]
The options file does get written over

**Comment by DocCyblade** [comment]
All files in pack get written over. Will need to put a blurb in the release notes to backup your option.txt file before upgrading.
