### ISSUE TITLE
Allow Extreme Reactors Ores  Anglesite and Benitoite to be useful

### ISSUE THREAD

**Issue by FreakinKen** [DocCyblade/squirrelpak-mc12#60]
There is no way to process Anglesite Ore or Benitoite Ore. These ores don't have any uses through JEI. More testing to continue. Initial suggestion would be to eliminate the generation of these ores.

**Comment by DocCyblade** [comment]
We could use Anglesite to make lead make up a use for it - IRL this is where lead comes from

**Comment by DocCyblade** [comment]
Benitoite we could use it to make titanium
